filebeat.inputs:
  - type: docker
    containers:
      ids:
        - '*'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: 'elastic'
  password: 'Test123'
  indices:
    - index: "filebeat-%{[agent.version]}"

logging.json: true
logging.metrics.enabled: false
