version: '3'

tasks:
  build:
    cmds:
      - go build

  run:
    cmds:
      - ./webhook-logger

  up:
    cmds:
      - docker-compose up --build webhook-logger

  clean:
    cmds:
      - docker-compose down --remove-orphans
