version: '3'

tasks:
  build:
    cmds:
      - go build

  run:
    cmds:
      - ./webhook-logger

  up:
    cmds:
      - docker-compose -f docker-compose.yml up --build webhook-logger
      
  up_elk:
    cmds:
      - docker-compose -f docker-compose-elk.yml up -d elasticsearch kibana filebeat
      
  down:
    cmds:
      - docker-compose down

  clean:
    cmds:
      - docker-compose down --remove-orphans
